# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EZtwittertool.ui'
#
# Created: Sun Dec 14 23:36:35 2014
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui, QtWebKit
import sys
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(QtGui.QWidget):

    def __init__(self):
        QtGui.QWidget.__init__(self)
        self.setupUi(self)



    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1261, 860)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("twitter images/twitter-big.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.verticalLayout_3 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Twitter_tab = QtGui.QWidget()
        self.Twitter_tab.setObjectName(_fromUtf8("Twitter_tab"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.Twitter_tab)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.back_btn_2 = QtGui.QPushButton(self.Twitter_tab)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("twitter images/back.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back_btn_2.setIcon(icon1)
        self.back_btn_2.setObjectName(_fromUtf8("back_btn_2"))
        self.horizontalLayout.addWidget(self.back_btn_2)
        self.refresh_btn_2 = QtGui.QPushButton(self.Twitter_tab)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("twitter images/refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refresh_btn_2.setIcon(icon2)
        self.refresh_btn_2.setObjectName(_fromUtf8("refresh_btn_2"))
        self.horizontalLayout.addWidget(self.refresh_btn_2)
        self.url_line = QtGui.QLineEdit(self.Twitter_tab)
        self.url_line.setObjectName(_fromUtf8("url_line"))
        self.horizontalLayout.addWidget(self.url_line)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.go_btn = QtGui.QPushButton(self.Twitter_tab)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("twitter images/twitter_standing.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.go_btn.setIcon(icon3)
        self.go_btn.setObjectName(_fromUtf8("go_btn"))
        self.horizontalLayout.addWidget(self.go_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_9.addLayout(self.verticalLayout_2)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.webView = QtWebKit.QWebView(self.Twitter_tab)
        self.webView.setUrl(QtCore.QUrl(_fromUtf8("https://twitter.com/")))
        self.webView.setObjectName(_fromUtf8("webView"))
        self.horizontalLayout_8.addWidget(self.webView)
        self.verticalLayout_10.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem2 = QtGui.QSpacerItem(300, 0, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.Delete_btn = QtGui.QPushButton(self.Twitter_tab)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("twitter images/red-delete-button.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Delete_btn.setIcon(icon4)
        self.Delete_btn.setObjectName(_fromUtf8("Delete_btn"))
        self.horizontalLayout_2.addWidget(self.Delete_btn)
        spacerItem3 = QtGui.QSpacerItem(100, 10, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.Accounts_btn = QtGui.QComboBox(self.Twitter_tab)
        self.Accounts_btn.setObjectName(_fromUtf8("Accounts_btn"))
        self.Accounts_btn.addItem(_fromUtf8(""))
        self.Accounts_btn.addItem(_fromUtf8(""))
        self.Accounts_btn.addItem(_fromUtf8(""))
        self.Accounts_btn.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.Accounts_btn)
        spacerItem4 = QtGui.QSpacerItem(300, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_9.addLayout(self.verticalLayout_5)
        self.verticalLayout_10.addLayout(self.horizontalLayout_9)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("twitter images/twitter.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.Twitter_tab, icon5, _fromUtf8(""))
        self.Message_tab = QtGui.QWidget()
        self.Message_tab.setObjectName(_fromUtf8("Message_tab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.Message_tab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.twitter_label = QtGui.QLabel(self.Message_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.twitter_label.sizePolicy().hasHeightForWidth())
        self.twitter_label.setSizePolicy(sizePolicy)
        self.twitter_label.setText(_fromUtf8(""))
        self.twitter_label.setPixmap(QtGui.QPixmap(_fromUtf8("twitter images/twitter_new_banner_620px.jpg")))
        self.twitter_label.setObjectName(_fromUtf8("twitter_label"))
        self.horizontalLayout_10.addWidget(self.twitter_label)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.handles_btn = QtGui.QToolButton(self.Message_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.handles_btn.sizePolicy().hasHeightForWidth())
        self.handles_btn.setSizePolicy(sizePolicy)
        self.handles_btn.setMaximumSize(QtCore.QSize(100, 16777215))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("twitter images/msn.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.handles_btn.setIcon(icon6)
        self.handles_btn.setPopupMode(QtGui.QToolButton.MenuButtonPopup)
        self.handles_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.handles_btn.setObjectName(_fromUtf8("handles_btn"))
        self.horizontalLayout_11.addWidget(self.handles_btn)
        self.line_2 = QtGui.QFrame(self.Message_tab)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_11.addWidget(self.line_2)
        self.message_btn = QtGui.QToolButton(self.Message_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.message_btn.sizePolicy().hasHeightForWidth())
        self.message_btn.setSizePolicy(sizePolicy)
        self.message_btn.setMaximumSize(QtCore.QSize(100, 16777215))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("twitter images/notepad.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.message_btn.setIcon(icon7)
        self.message_btn.setPopupMode(QtGui.QToolButton.MenuButtonPopup)
        self.message_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.message_btn.setObjectName(_fromUtf8("message_btn"))
        self.horizontalLayout_11.addWidget(self.message_btn)
        self.line = QtGui.QFrame(self.Message_tab)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_11.addWidget(self.line)
        self.dm_btn = QtGui.QPushButton(self.Message_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dm_btn.sizePolicy().hasHeightForWidth())
        self.dm_btn.setSizePolicy(sizePolicy)
        self.dm_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("twitter images/rss.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dm_btn.setIcon(icon8)
        self.dm_btn.setObjectName(_fromUtf8("dm_btn"))
        self.horizontalLayout_11.addWidget(self.dm_btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.pushButton_2 = QtGui.QPushButton(self.Message_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMaximumSize(QtCore.QSize(100, 16777215))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("twitter images/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon9)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.verticalLayout_11.addWidget(self.pushButton_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.treeWidget = QtGui.QTreeWidget(self.Message_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.treeWidget.header().setCascadingSectionResizes(False)
        self.treeWidget.header().setDefaultSectionSize(300)
        self.treeWidget.header().setMinimumSectionSize(33)
        self.horizontalLayout_12.addWidget(self.treeWidget)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("twitter images/email2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.Message_tab, icon10, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)



        QtCore.QObject.connect(self.back_btn_2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.webView.back)
        QtCore.QObject.connect(self.refresh_btn_2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.webView.reload)
        QtCore.QObject.connect(self.go_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), self.webView.forward)
        QtCore.QObject.connect(self.webView, QtCore.SIGNAL(_fromUtf8("titleChanged(QString)")), Form.setWindowTitle)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "EZ Twitter Tool ", None))
        self.back_btn_2.setText(_translate("Form", "Back", None))
        self.refresh_btn_2.setText(_translate("Form", "Refresh", None))
        self.go_btn.setText(_translate("Form", "Go", None))
        self.Delete_btn.setText(_translate("Form", "Delete", None))
        self.Accounts_btn.setItemText(0, _translate("Form", "Account 1", None))
        self.Accounts_btn.setItemText(1, _translate("Form", "Account 2", None))
        self.Accounts_btn.setItemText(2, _translate("Form", "Account 3", None))
        self.Accounts_btn.setItemText(3, _translate("Form", "Account 4", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Twitter_tab), _translate("Form", "Twitter", None))
        self.handles_btn.setText(_translate("Form", "Handles", None))
        self.message_btn.setText(_translate("Form", "Message", None))
        self.dm_btn.setText(_translate("Form", "Direct Message", None))
        self.pushButton_2.setText(_translate("Form", "Remove", None))
        self.treeWidget.headerItem().setText(0, _translate("Form", "Filename", None))
        self.treeWidget.headerItem().setText(1, _translate("Form", "File Type", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Message_tab), _translate("Form", "Message", None))




if __name__ == '__main__':
    app = QtGui.QApplication(sys.argv)
    ex = Ui_Form()
    ex.show()
    sys.exit(app.exec_())
